name: Koffietime App CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: |
        npm ci
        npm install
    - name: Run build
      run: |
        npm run build --if-present
    - name: Run unit tests
      run: |
        npm test -- --verbose --coverage --watchAll=false
    - name: Run linting
      run: |
        npm install lint
        npm lint
      env:
        CI: true
